"""Media storage for uploaded assets (Sprint 3): hero-image validation + disk."""

from app.media.hero import (
    GALLERY_MAX_BYTES,
    GALLERY_MIN_HEIGHT,
    GALLERY_MIN_WIDTH,
    GALLERY_OUT_MAX_WIDTH,
    GALLERY_OUT_QUALITY,
    HERO_MAX_BYTES,
    HERO_MIN_HEIGHT,
    HERO_MIN_WIDTH,
    HERO_OUT_MAX_WIDTH,
    HERO_OUT_QUALITY,
    HeroImageError,
    reencode_image,
    read_upload_limited,
    save_hero_image,
    save_region_hero_image,
    save_spot_image,
    validate_gallery_image,
    validate_hero_image,
)
from app.media.image_object import (
    CANONICAL_KEYS,
    CENTER_FOCAL,
    DELIVERIES,
    PROVIDERS,
    RIGHTS_FIELDS,
    ROLES,
    ImageObjectError,
    build_image,
    is_placeholder,
    normalize_focal,
    placeholder_image,
    upgrade_legacy,
    utc_now_iso,
    with_fields,
)
from app.media.license import (
    IMAGE_LICENSE_TERMS,
    IMAGE_LICENSE_VERSION,
    license_terms,
)
from app.media.storage import delete_url

__all__ = [
    "HERO_MAX_BYTES",
    "HERO_MIN_HEIGHT",
    "HERO_MIN_WIDTH",
    "HERO_OUT_MAX_WIDTH",
    "HERO_OUT_QUALITY",
    "GALLERY_MAX_BYTES",
    "GALLERY_MIN_HEIGHT",
    "GALLERY_MIN_WIDTH",
    "GALLERY_OUT_MAX_WIDTH",
    "GALLERY_OUT_QUALITY",
    "HeroImageError",
    "reencode_image",
    "read_upload_limited",
    "save_hero_image",
    "save_region_hero_image",
    "save_spot_image",
    "validate_gallery_image",
    "validate_hero_image",
    "IMAGE_LICENSE_TERMS",
    "IMAGE_LICENSE_VERSION",
    "license_terms",
    "delete_url",
    "CANONICAL_KEYS",
    "CENTER_FOCAL",
    "DELIVERIES",
    "PROVIDERS",
    "RIGHTS_FIELDS",
    "ROLES",
    "ImageObjectError",
    "build_image",
    "is_placeholder",
    "normalize_focal",
    "placeholder_image",
    "upgrade_legacy",
    "utc_now_iso",
    "with_fields",
]
