import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page } from "@playwright/test";

const spot={id:"test",slug:"laboe",name:"Laboe",region_id:"r1",location:{lat:54.4,lon:10.2},sports:["surf"],water_type:["sea"],bottom_type:["sand"],level:["advanced"],water_character:["welle_klein"],style:["wave_riding"],facilities:null,status:"published",confidence:null,facing:45,image:null,era5_cell:null,model_pref:null,editorial:{description:"Testspot"},climatology:null,overrides:null,finish_rank:null,created_at:"2026-01-01T00:00:00Z",updated_at:"2026-08-24T00:00:00Z"};
const summary={wind_avg:12,wind_max:18,gust_max:24,air_min:12,air_max:21,swell_max:1.8};
const hourly=Array.from({length:5},(_,day)=>{const date=`2026-08-${String(24+day).padStart(2,"0")}`;return {date,local_date:date,detail:"hourly",confidence:day<2?"hoch":"mittel",summary,hours:Array.from({length:8},(_,slot)=>({time:`${date}T${String(slot*3).padStart(2,"0")}:00:00Z`,wind:10+slot,gust:15+slot,dir:(180+slot*10)%360,air:14+slot,precip:slot===2?3:0,swell:1.2+slot/10,period:7+slot/2,swell_dir:270,sst:18,weather_condition:slot===2?"rain":"partly_cloudy",is_day:slot>1&&slot<7,wind_spread:{low:8+slot,median:10+slot,high:13+slot,n:3}}))};});
const trend=Array.from({length:5},(_,day)=>{const date=new Date(Date.UTC(2026,7,29+day)).toISOString().slice(0,10);return {date,local_date:date,detail:"trend",confidence:"niedrig",summary,hours:[]};});
const forecast={spot_id:"test",model:"consensus",product:"Surfwinddata Forecast",generated_at:"2026-08-24T08:00:00Z",updated_at:"2026-08-24T08:00:00Z",timezone:"Europe/Berlin",stale:true,availability:{atmosphere:"available",solar:"available",marine:"available_stale" as string},days:[...hourly,...trend]};

async function mockApi(page:Page,forecastPayload:typeof forecast=forecast){await page.route(/^http:\/\/(?:localhost|127\.0\.0\.1):8000\//,(route)=>{const path=new URL(route.request().url()).pathname;if(["/spots/test","/spots/laboe","/spots/Laboe"].includes(path))return route.fulfill({json:spot});if(path==="/regions/r1")return route.fulfill({json:{id:"r1",slug:"kieler-bucht",name:"Kieler Bucht",country:"DE",center:null,description:null,image:null,season:null,defaults:null,status:"published",updated_at:"2026-08-24T00:00:00Z"}});if(path==="/spots/test/forecast")return route.fulfill({json:forecastPayload});if(path==="/spots/test/live"||path==="/spots/test/tides")return route.fulfill({status:404,json:{detail:"none"}});if(path==="/spots/test/ratings")return route.fulfill({json:{items:[],aggregate:{count:0,average:null}}});if(path==="/spots/test/tips"||path==="/spots/test/images")return route.fulfill({json:[]});return route.fulfill({status:404,json:{detail:`mock missing: ${path}`}});});}

for(const width of [320,375,390,768,1280,1440])test(`Meteogramm bleibt bei ${width}px innerhalb der Seite`,async({page})=>{await page.setViewportSize({width,height:width===320?568:width===375?667:width===390?844:width===768?1024:width===1280?800:900});if(width===390)await page.emulateMedia({colorScheme:"light"});await mockApi(page);await page.goto("/spot/test/daten");await expect(page.getByRole("heading",{name:"Stundenprognose · Tage 1–5"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);if(width<768)await expect(page.getByRole("button",{name:"24 h"})).toHaveAttribute("aria-pressed","true");if(width===390)await page.screenshot({path:"test-results/meteogram-mobile-light.png",fullPage:true});});

test("Zeitraum, Tages- und UTC-Auswahl sind per Tastatur und Pointer kontrollierbar",async({page})=>{await page.setViewportSize({width:390,height:900});await mockApi(page);await page.goto("/spot/test/daten");const mode48=page.getByRole("button",{name:"48 h"});await mode48.focus();await page.keyboard.press("Enter");await expect(mode48).toHaveAttribute("aria-pressed","true");await page.getByRole("button",{name:"Nächster Prognosetag"}).click();await expect(page.getByText(/Dienstag, 25\.08\./)).toBeVisible();await expect(page.getByText(/Auswahl · 2026-08-25/)).toBeVisible();const next=page.getByRole("button",{name:"Nächster Zeitpunkt"});await next.focus();await page.keyboard.press("Space");await expect(page.getByText(/Auswahl · 2026-08-25/)).toBeVisible();await page.locator("g[data-utc]").nth(2).click();await expect(page.getByText(/Auswahl · 2026-08-25 · 08:00/)).toBeVisible();const hit=page.locator("g[data-utc]").nth(3);await hit.dispatchEvent("click",{pointerType:"touch"});await expect(page.getByText(/Auswahl · 2026-08-25 · 11:00/)).toBeVisible();});

test("TimeScrubber synchronisiert Meteogramm, LiveRow und Karte per Tastatur",async({page})=>{await page.setViewportSize({width:1280,height:800});await mockApi(page);await page.goto("/spot/test/daten");const slider=page.getByRole("slider",{name:"Prognosezeitpunkt"});await slider.focus();const before=await slider.getAttribute("aria-valuenow");await page.keyboard.press("ArrowRight");await expect(slider).not.toHaveAttribute("aria-valuenow",before??"");const consumers=page.locator("[data-forecast-utc]");await expect(consumers).toHaveCount(3);const keys=await consumers.evaluateAll((nodes)=>nodes.map((node)=>node.getAttribute("data-forecast-utc")));expect(new Set(keys).size).toBe(1);expect(keys[0]).not.toBe("");});

test("Datentabelle ist vollständig, zoombar und axe-konform",async({page})=>{await page.setViewportSize({width:390,height:900});await page.emulateMedia({reducedMotion:"reduce",colorScheme:"dark"});await mockApi(page);await page.goto("/spot/test/daten");const toggle=page.getByRole("button",{name:/Daten als Tabelle/});await toggle.click();await expect(toggle).toHaveAttribute("aria-expanded","true");const table=page.getByRole("table",{name:/Vollständige Stundenprognose/});await expect(table).toBeVisible();await expect(table.getByRole("columnheader",{name:"Modellspanne"})).toBeVisible();await expect(table.getByText("8 kt bis 13 kt (3 Modelle)").first()).toBeVisible();const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter((item)=>["serious","critical"].includes(item.impact??""))).toEqual([]);await page.screenshot({path:"test-results/meteogram-390-dark-table.png",fullPage:true});await page.evaluate(()=>{document.documentElement.style.zoom="2";});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);});

test("Desktopansicht und Light Mode behalten fünf Detailtage",async({page})=>{await page.setViewportSize({width:1280,height:900});await page.emulateMedia({colorScheme:"light"});await mockApi(page);await page.goto("/spot/test/daten");await expect(page.getByRole("button",{name:"5 Tage"})).toHaveAttribute("aria-pressed","true");await expect(page.getByText("Tagestrend · Tage 6–10")).toBeVisible();await page.screenshot({path:"test-results/meteogram-desktop-light.png",fullPage:true});});

test("Datenlücken bleiben sichtbar und verbinden keine Temperatursegmente",async({page})=>{const gaps=structuredClone(forecast);gaps.availability.marine="unavailable_provider";gaps.days[0].hours[2].air=null;gaps.days[0].hours[2].precip=null;gaps.days[0].hours[2].wind=null;gaps.days[0].hours[2].gust=null;gaps.days[0].hours[2].swell=null;gaps.days[0].hours[2].period=null;await page.setViewportSize({width:768,height:1024});await mockApi(page,gaps);await page.goto("/spot/test/daten");await expect(page.getByText(/Marineprognose ist beim Datenanbieter/)).toBeVisible();await page.getByRole("button",{name:/Daten als Tabelle/}).click();await expect(page.getByText(/Teilweise verfügbar · fehlt:/).first()).toBeVisible();await page.screenshot({path:"test-results/meteogram-data-gaps.png",fullPage:true});});
