// How a hero image is actually fetched, decided by `delivery`.
//
// `hosted` — the bytes are in our own storage; the build-time manifest supplies
// AVIF/WebP variants where they exist.
// `hotlinked` — the bytes stay on the provider's CDN because their terms
// require it (Unsplash). Their CDN takes sizing parameters, so we can still
// serve a right-sized image without hosting anything.

/** Widths requested from a provider CDN, matching common hero display sizes. */
export const CDN_WIDTHS = [640, 1024, 1600, 2400, 3840] as const;

/** Smaller widths for browse cards. Even on a high-DPI desktop a card is
 * nowhere near hero size; keeping this list separate prevents a 3840 px source
 * from being selected for a roughly 300 px tile. */
export const CARD_CDN_WIDTHS = [320, 480, 640, 960] as const;

/** Width ladder generated by app/media/hero.py for newly hosted uploads. */
export const HOSTED_IMAGE_WIDTHS = [480, 768, 1280, 1920] as const;
const RESPONSIVE_MARKER = "-responsive";

/** Unsplash CDN parameters: width, quality, format, and never upscale. */
export function unsplashSized(url: string, width: number): string {
  const [base, hash] = url.split("#");
  const separator = base.includes("?") ? "&" : "?";
  const sized = `${base}${separator}w=${width}&q=80&fm=jpg&fit=max`;
  return hash ? `${sized}#${hash}` : sized;
}

/**
 * A width-descriptor srcset for a hotlinked provider image.
 *
 * Returns undefined for anything we do not know how to resize — guessing at
 * another CDN's parameter names would produce broken URLs, and a plain <img>
 * is a perfectly good fallback.
 */
export function hotlinkSrcSet(url: string, provider?: string | null): string | undefined {
  if (provider !== "unsplash") return undefined;
  return CDN_WIDTHS.map((width) => `${unsplashSized(url, width)} ${width}w`).join(", ");
}

/** Responsive srcset for a spot/region card rather than a full-bleed hero. */
export function cardHotlinkSrcSet(url: string): string | undefined {
  try {
    if (new URL(url).hostname !== "images.unsplash.com") return undefined;
  } catch {
    return undefined;
  }
  return CARD_CDN_WIDTHS.map((width) => `${unsplashSized(url, width)} ${width}w`).join(", ");
}

function hostedVariantWidths(url: string): readonly number[] | undefined {
  const match = url.match(/^([^?#]+)(\?[^#]*)?(#.*)?$/);
  if (!match) return undefined;
  const path = match[1];
  const dot = path.lastIndexOf(".");
  if (dot < 0) return undefined;
  const suffix = path.slice(0, dot);
  if (suffix.endsWith(RESPONSIVE_MARKER)) return HOSTED_IMAGE_WIDTHS;
  const token = suffix.match(/-responsive-(none|[1-9]\d*(?:_[1-9]\d*)*)$/)?.[1];
  if (!token) return undefined;
  return token === "none" ? [] : token.split("_").map(Number);
}

function hostedVariantUrl(url: string, width: number): string | undefined {
  const match = url.match(/^([^?#]+)(\?[^#]*)?(#.*)?$/);
  if (!match) return undefined;
  const path = match[1];
  const dot = path.lastIndexOf(".");
  if (dot < 0) return undefined;
  return `${path.slice(0, dot)}-w${width}${path.slice(dot)}${match[2] ?? ""}${match[3] ?? ""}`;
}

/** Width-descriptor srcset for a responsive image set created by the API.
 * Legacy hosted URLs have no marker and intentionally fall back to one src. */
export function hostedSrcSet(url: string, width?: number | null): string | undefined {
  if (!width || width <= 0) return undefined;
  const availableWidths = hostedVariantWidths(url);
  if (!availableWidths) return undefined;
  const variants = availableWidths
    .filter((candidate) => candidate < width)
    .map((candidate) => {
      const candidateUrl = hostedVariantUrl(url, candidate);
      return candidateUrl ? `${candidateUrl} ${candidate}w` : null;
    })
    .filter((candidate): candidate is string => Boolean(candidate));
  if (variants.length === 0) return undefined;
  return [...variants, `${url} ${width}w`].join(", ");
}

export function responsiveImageAttributes(
  url: string | undefined,
  width: number | null | undefined,
  sizes: string,
): { src?: string; srcSet?: string; sizes?: string } {
  if (!url) return {};
  const srcSet = hostedSrcSet(url, width);
  return { src: url, srcSet, sizes: srcSet ? sizes : undefined };
}

/** Focal point → CSS object-position. Percentages, as stored. */
export function objectPosition(focal?: { x: number; y: number } | null): string | undefined {
  if (!focal) return undefined;
  return `${focal.x}% ${focal.y}%`;
}
